// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7npwkLavv-ZfmWJ8VrPXPrsSbjZo19ms',
    appId: '1:818483931315:web:91ff044fc1a0eb6200e8c6',
    messagingSenderId: '818483931315',
    projectId: 'book-store-59a17',
    authDomain: 'book-store-59a17.firebaseapp.com',
    storageBucket: 'book-store-59a17.appspot.com',
    measurementId: 'G-YNKFPVEW0E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvLPqgRv3tuanNU3bMEy8w68qVEoaTv3g',
    appId: '1:818483931315:android:bafbcdf97aa4019600e8c6',
    messagingSenderId: '818483931315',
    projectId: 'book-store-59a17',
    storageBucket: 'book-store-59a17.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmLFSjsopeeJEAf9h7Dj-2AhgmuXTo-R8',
    appId: '1:818483931315:ios:e15cd7d6d378254e00e8c6',
    messagingSenderId: '818483931315',
    projectId: 'book-store-59a17',
    storageBucket: 'book-store-59a17.appspot.com',
    iosClientId: '818483931315-dh1crn6jh4ggps25b27nri9eihjktc77.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookStore',
  );
}
